name: SunwayMinecraft
version: '1.0-SNAPSHOT'
main: com.sunwayMinecraft.SunwayMinecraft
api-version: '1.20'

commands:
  pausebeacons:
    description: "Pause the beacon color transitions."
    usage: "/pausebeacons"
    permission: "sunwayminecraft.beacons.pause"

  resumebeacons:
    description: "Resume the beacon color transitions."
    usage: "/resumebeacons"
    permission: "sunwayminecraft.beacons.resume"

  reloadsunwayconfig:
    description: "Reloads the SunwayMinecraft plugin configuration."
    usage: "/reloadsunwayconfig"
    permission: "sunwayminecraft.config.reload"

  setbeaconticks:
    description: "Set the number of ticks per beacon color transition."
    usage: "/setbeaconticks <ticks>"
    permission: "sunwayminecraft.beacons.setticks"

  reloadsunwaybenches:
    description: "Reload bench configurations"
    usage: "/reloadsunwaybenches"
    permission: "sunwayminecraft.benches.reload"

permissions:
  sunwayminecraft.beacons.pause:
    description: "Allows the user to pause beacon color transitions."
    default: op

  sunwayminecraft.beacons.resume:
    description: "Allows the user to resume beacon color transitions."
    default: op

  sunwayminecraft.config.reload:
    description: "Allows the user to reload the SunwayMinecraft plugin configuration."
    default: op

  sunwayminecraft.beacons.setticks:
    description: "Allows setting the number of ticks per beacon color transition."
    default: op

  sunwayminecraft.benches.reload:
    description: "Allows reloading bench configurations"
    default: op
