package com.sunwayMinecraft.residency.domain;

public enum ActionType {
    ENTER,
    OPEN_DOOR,
    USE_CONTAINER,
    PLACE_BLOCK,
    BREAK_BLOCK,
    USE_BUTTON_OR_LEVER,
    INTERACT_ENTITY,
    MODIFY_ITEM_FRAME,
    MODIFY_ARMOR_STAND,
    USE_BED,
    INTERACT_PET,
    USE_REDSTONE_SENSITIVE,
    MANAGE_GUESTS,
    MANAGE_UNIT_SETTINGS,
    MANAGE_STORE_STATUS,
    START_EVENT_ACCESS,
    VIEW_DIRECTORY_PRIVATE_INFO
}
